// src/context/todo/todoTypes.js
export const TODO_ACTIONS = {
    STATE_RESET: "STATE/RESET",
    ERROR_CLEAR: "ERROR/CLEAR",

    FILTER_SET: "TODO/FILTER/SET",

    FETCH_REQUEST_START: "TODO/FETCH/REQUEST_START",
    FETCH_SUCCESS: "TODO/FETCH/SUCCESS",
    FETCH_FAIL: "TODO/FETCH/FAIL",

    CREATE_OPTIMISTIC_ADD: "TODO/CREATE/OPTIMISTIC_ADD",
    CREATE_OPTIMISTIC_COMMIT: "TODO/CREATE/OPTIMISTIC_COMMIT",
    CREATE_OPTIMISTIC_ROLLBACK: "TODO/CREATE/OPTIMISTIC_ROLLBACK",

    DELETE_OPTIMISTIC_REMOVE: "TODO/DELETE/OPTIMISTIC_REMOVE",
    DELETE_OPTIMISTIC_ROLLBACK: "TODO/DELETE/OPTIMISTIC_ROLLBACK",

    TOGGLE_OPTIMISTIC_FLIP: "TODO/TOGGLE/OPTIMISTIC_FLIP",
    TOGGLE_OPTIMISTIC_ROLLBACK: "TODO/TOGGLE/OPTIMISTIC_ROLLBACK",

    EDIT_OPTIMISTIC_UPDATE: "TODO/EDIT/OPTIMISTIC_UPDATE",
    EDIT_OPTIMISTIC_ROLLBACK: "TODO/EDIT/OPTIMISTIC_ROLLBACK",
};
